"""followers

Revision ID: 134a978a4b62
Revises: cdc03334b906
Create Date: 2018-03-19 14:04:13.386217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134a978a4b62'
down_revision = 'cdc03334b906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
